ip_extractor:
  ip_page_url: 'https://ip.neu.edu.cn/'
  regex_pattern: '((2(5[0-5]|[0-4]\d))|[0-1]?\d{1,2})(\.((2(5[0-5]|[0-4]\d))|[0-1]?\d{1,2})){3}'
  ac_id_wireless: 15
  ac_id_wired: 1

ipgw_login:
  login_url_template: 'https://pass.neu.edu.cn/tpass/login?service=http://ipgw.neu.edu.cn/srun_portal_sso?ac_id=%s'
  default_ac_ids: [ 15, 1 ]
  timeout: 10000

application:
  check_interval_ms: 15000  # 15 seconds
  retry_delay_ms: 5000       # 5 seconds
  max_retries: 3

network_check:
  default_check_url: 'https://www.baidu.com'
  timeout_ms: 5000  # 超时时间，单位毫秒

credentials:
  username: ""
  password: ""